# Generated by Django 6.0.6 on 2026-06-18 11:14

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(db_index=True)),
                ('check_in_time', models.DateTimeField()),
                ('check_in_location', django.contrib.gis.db.models.fields.PointField(help_text='GPS coordinates (longitude, latitude)', srid=4326)),
                ('selfie_image', models.URLField(blank=True, null=True)),
                ('selfie_verified', models.BooleanField(default=True)),
                ('face_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half-day', 'Half-day'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('sync_id', models.UUIDField(help_text='Idempotency key for offline sync', unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee Attendance',
                'verbose_name_plural': 'Employee Attendances',
            },
        ),
    ]
