# Generated by Django 6.0.6 on 2026-06-18 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='sites.site'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['employee', 'work_date'], name='attendance__employe_c15c68_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['site', 'work_date'], name='attendance__site_id_79f860_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['sync_id'], name='attendance__sync_id_372f51_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'work_date'), name='unique_employee_attendance_per_day'),
        ),
    ]
