# Generated by Django 6.0.6 on 2026-06-23 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('sites', '0006_siteassignment_end_date_siteassignment_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={'ordering': ['-work_date', '-check_in_time'], 'verbose_name': 'Employee Attendance', 'verbose_name_plural': 'Employee Attendances'},
        ),
        migrations.RemoveConstraint(
            model_name='employeeattendance',
            name='unique_employee_attendance_per_day',
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'work_date', 'site'), name='unique_employee_attendance_per_site_per_day'),
        ),
    ]
