/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#98805d",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#574425",
        "on-error": "#ffffff",
        "on-surface": "#191c1e",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        "text-muted": "#64748B",
        "status-completed": "#3B82F6",
        "primary-container": "#131b2e",
        "inverse-surface": "#2d3133",
        "surface-container-high": "#e6e8ea",
        "on-secondary-container": "#5c2400",
        "surface-container-lowest": "#ffffff",
        "background": "#f7f9fb",
        "on-surface-variant": "#45464d",
        "inverse-primary": "#bec6e0",
        "surface": "#f7f9fb",
        "outline": "#76777d",
        "text-main": "#1E293B",
        "on-secondary-fixed": "#341100",
        "border-subtle": "#E2E8F0",
        "primary": "#000000",
        "primary-fixed-dim": "#bec6e0",
        "secondary": "#9d4300",
        "on-primary-container": "#7c839b",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed-variant": "#3f465c",
        "status-active": "#22C55E",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
        "status-on-hold": "#FACC15",
        "on-secondary-fixed-variant": "#783200",
        "surface-tint": "#565e74",
        "surface-container": "#eceef0",
        "on-primary-fixed": "#131b2e",
        "primary-fixed": "#dae2fd",
        "tertiary-fixed": "#fcdeb5",
        "outline-variant": "#c6c6cd",
        "secondary-fixed-dim": "#ffb690",
        "on-tertiary-fixed": "#271901",
        "secondary-container": "#fd761a",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#ffdbca",
        "surface-container-low": "#f2f4f6",
        "on-tertiary": "#ffffff",
        "tertiary": "#000000",
        "error": "#ba1a1a",
        "tertiary-container": "#271901",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed-dim": "#dec29a",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "container-padding": "24px",
        "table-row-standard": "12px",
        "table-row-condensed": "8px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["11px", {"lineHeight": "16px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "title-lg": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
