# Generated by Django 6.0.6 on 2026-06-18 11:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='GPS coordinates (longitude, latitude)', srid=4326)),
                ('geofence_radius_meters', models.IntegerField(default=50)),
                ('attendance_cutoff_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'indexes': [models.Index(fields=['name'], name='sites_site_name_1ba0c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Assignment',
                'verbose_name_plural': 'Site Assignments',
            },
        ),
    ]
