# Generated by Django 6.0.6 on 2026-06-18 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='siteassignment',
            constraint=models.UniqueConstraint(fields=('user', 'site'), name='unique_user_site_assignment'),
        ),
    ]
