# Generated by Django 6.0.6 on 2026-06-19 11:29

import apps.sites.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAttendanceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_radius', models.IntegerField(default=50, help_text='Radius in meters')),
                ('cutoff_time', models.TimeField(default='09:30:00')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Attendance Setting',
                'verbose_name_plural': 'Site Attendance Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.sites.models.upload_site_document_path)),
                ('document_type', models.CharField(choices=[('Agreement', 'Agreement'), ('Drawings', 'Drawings'), ('Approvals', 'Approvals'), ('Blueprints', 'Blueprints')], max_length=50)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sites.site')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Document',
                'verbose_name_plural': 'Site Documents',
            },
        ),
        migrations.CreateModel(
            name='SiteEngineerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_engineers', to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_engineer_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Engineer Assignment',
                'verbose_name_plural': 'Site Engineer Assignments',
            },
        ),
    ]
