# Generated by Django 6.0.6 on 2026-06-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_siteattendancesettings_sitedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='target_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
