# Generated by Django 6.0.6 on 2026-06-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_site_notes_site_start_date_site_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='site',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='site',
            name='status',
        ),
        migrations.RemoveField(
            model_name='site',
            name='target_end_date',
        ),
    ]
