# Generated by Django 6.0.6 on 2026-06-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_remove_site_notes_remove_site_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
