# Generated by Django 6.0.6 on 2026-06-24 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_sitelevel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelevel',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitelevel',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
