# Generated by Django 6.0.6 on 2026-06-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_sitelevel_assigned_to_sitelevel_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
