# Generated by Django 6.0.6 on 2026-06-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Civil', 'Civil'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Safety', 'Safety'), ('Quality', 'Quality'), ('HR', 'HR'), ('Accounts', 'Accounts'), ('Administration', 'Administration')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('Site Engineer', 'Site Engineer'), ('Project Manager', 'Project Manager'), ('Supervisor', 'Supervisor'), ('Civil Engineer', 'Civil Engineer'), ('Electrical Engineer', 'Electrical Engineer'), ('HR Executive', 'HR Executive'), ('Accountant', 'Accountant')], max_length=50, null=True),
        ),
    ]
