# Generated by Django 6.0.6 on 2026-06-24 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('sites', '0008_sitelevel_assigned_to_sitelevel_target_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('liters_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slip_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=200, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diesel_logs', to='equipment.equipment')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diesel_logs', to='sites.site')),
            ],
            options={
                'verbose_name': 'Diesel Log',
                'verbose_name_plural': 'Diesel Logs',
                'indexes': [models.Index(fields=['site', 'date'], name='equipment_d_site_id_e1c86f_idx')],
            },
        ),
    ]
