# Generated by Django 6.0.6 on 2026-06-24 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('sites', '0008_sitelevel_assigned_to_sitelevel_target_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, help_text='Amount received for petty cash / expenses', max_digits=12)),
                ('particulars', models.CharField(help_text='Amount Received by / Expenses Particulars', max_length=500)),
                ('expense_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Expense',
                'verbose_name_plural': 'Site Expenses',
                'indexes': [models.Index(fields=['site', 'date'], name='finance_sit_site_id_b682c8_idx')],
            },
        ),
    ]
