# Generated by Django 6.0.6 on 2026-06-18 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labour_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('skill_type', models.CharField(choices=[('Mason', 'Mason'), ('Carpenter', 'Carpenter'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Helper', 'Helper'), ('Painter', 'Painter'), ('Others', 'Others')], db_index=True, max_length=50)),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
            options={
                'verbose_name': 'Labour',
                'verbose_name_plural': 'Labours',
                'indexes': [models.Index(fields=['labour_code'], name='labour_labo_labour__834fc5_idx'), models.Index(fields=['skill_type'], name='labour_labo_skill_t_08202c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabourAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half-day', 'Half-day')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sync_id', models.UUIDField(help_text='Idempotency key for offline sync', unique=True)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='labour.labour')),
            ],
            options={
                'verbose_name': 'Labour Attendance',
                'verbose_name_plural': 'Labour Attendances',
            },
        ),
    ]
