# Generated by Django 6.0.6 on 2026-06-18 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labour', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labourattendance',
            name='marked_by_engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_labour_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labourattendance',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_attendances', to='sites.site'),
        ),
        migrations.AddIndex(
            model_name='labourattendance',
            index=models.Index(fields=['labour', 'date'], name='labour_labo_labour__43ce5a_idx'),
        ),
        migrations.AddIndex(
            model_name='labourattendance',
            index=models.Index(fields=['site', 'date'], name='labour_labo_site_id_88d8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='labourattendance',
            index=models.Index(fields=['sync_id'], name='labour_labo_sync_id_edfdfc_idx'),
        ),
        migrations.AddConstraint(
            model_name='labourattendance',
            constraint=models.UniqueConstraint(fields=('labour', 'date'), name='unique_labour_attendance_per_day'),
        ),
    ]
