# Generated by Django 6.0.6 on 2026-06-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0002_initial'),
        ('sites', '0003_siteattendancesettings_sitedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_labours', to='sites.site'),
        ),
    ]
