# Generated by Django 6.0.6 on 2026-06-24 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0003_labour_site'),
        ('sites', '0006_siteassignment_end_date_siteassignment_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourGroupPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_url', models.URLField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_group_photos', to='sites.site')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_group_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labour Group Photo',
                'verbose_name_plural': 'Labour Group Photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
