# Generated by Django 6.0.6 on 2026-06-18 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySiteReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(db_index=True)),
                ('work_summary', models.TextField()),
                ('issues_faced', models.TextField(blank=True, null=True)),
                ('sync_id', models.UUIDField(help_text='Idempotency key for offline sync', unique=True)),
            ],
            options={
                'verbose_name': 'Daily Site Report',
                'verbose_name_plural': 'Daily Site Reports',
            },
        ),
        migrations.CreateModel(
            name='SiteReportImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Report Image',
                'verbose_name_plural': 'Site Report Images',
            },
        ),
    ]
