# Generated by Django 6.0.6 on 2026-06-18 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysitereport',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitereportimage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.dailysitereport'),
        ),
        migrations.AddIndex(
            model_name='dailysitereport',
            index=models.Index(fields=['site', 'report_date'], name='reports_dai_site_id_144f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysitereport',
            index=models.Index(fields=['sync_id'], name='reports_dai_sync_id_b7e499_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailysitereport',
            constraint=models.UniqueConstraint(fields=('site', 'report_date'), name='unique_site_report_per_day'),
        ),
    ]
