# Generated by Django 6.0.6 on 2026-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitereportimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='dailysitereport',
            name='labour_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysitereport',
            name='material_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysitereport',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='0-100'),
        ),
        migrations.AddField(
            model_name='sitereportimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report_images/'),
        ),
    ]
