# Generated by Django 6.0.6 on 2026-06-24 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_sitereportimage_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPREquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_supplier_name', models.CharField(max_length=255)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_details', to='reports.dailysitereport')),
            ],
        ),
        migrations.CreateModel(
            name='DPRExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('particulars', models.CharField(max_length=500)),
                ('expense_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_details', to='reports.dailysitereport')),
            ],
        ),
        migrations.CreateModel(
            name='DPRManpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_labour', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_details', to='reports.dailysitereport')),
            ],
        ),
        migrations.CreateModel(
            name='DPRMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_details', to='reports.dailysitereport')),
            ],
        ),
        migrations.CreateModel(
            name='DPRPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_activity', models.CharField(max_length=500)),
                ('requirements', models.CharField(blank=True, max_length=500, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_details', to='reports.dailysitereport')),
            ],
        ),
        migrations.CreateModel(
            name='DPRWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_work', models.CharField(max_length=500)),
                ('nos', models.IntegerField(blank=True, default=0, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='reports.dailysitereport')),
            ],
        ),
    ]
