# Generated by Django 6.0.6 on 2026-06-18 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('sync_id', models.UUIDField(help_text='Idempotency key for offline sync', unique=True)),
            ],
            options={
                'verbose_name': 'GPS Log',
                'verbose_name_plural': 'GPS Logs',
            },
        ),
    ]
