# Generated by Django 6.0.6 on 2026-06-18 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gps_tracking', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gpslog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_logs', to='sites.site'),
        ),
        migrations.AddIndex(
            model_name='gpslog',
            index=models.Index(fields=['employee', 'timestamp'], name='gps_trackin_employe_d8b86d_idx'),
        ),
        migrations.AddIndex(
            model_name='gpslog',
            index=models.Index(fields=['sync_id'], name='gps_trackin_sync_id_448fe0_idx'),
        ),
    ]
